name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v5

      - name: Configurar JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Dar permisos de ejecución al Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar, probar y empaquetar
        run: ./mvnw clean package

      - name: Subir el empaquetado (.jar / .war) como Artefacto
        uses: actions/upload-artifact@v5
        with:
          name: app-backend
          path: target/*.jar  # Cambia a target/*.war si estás generando un WAR
          retention-days: 7